export const USER_PROFILE_SUCCEED = 'user/profile'
export const USER_UPDATE_PHOTO_SUCCEED = 'user/updatePhoto'
export const USER_FETCHING = 'user/fetching'
export const USER_CLEAR = 'user/clear'
export const USER_ERROR = 'user/error'
