export const CAR_FETCHING = 'car/fetching'
export const CAR_CARS_SUCCEED = 'car/cars'
export const CAR_CURRENT_SUCCEED = 'car/current'
export const CAR_PUSH_SUCCEED = 'car/push'
export const CAR_FILTER_SUCCEED = 'car/filter'
export const CAR_REPLACE_SUCCEED = 'car/replace'
export const CAR_ERROR = 'car/error'
export const CAR_NOTE_PULL_SUCCEED = 'car/pullNote'
export const CAR_NOTE_REPLACE_SUCCEED = 'car/replaceNote'

