export const CAR_FETCHING = 'car/fetching'
export const CAR_CARS_SUCCEED = 'car/cars'
export const CAR_CURRENT_SUCCEED = 'car/current'
export const CAR_FILTER_SUCCEED = 'car/filterCars'
export const CAR_REPLACE_SUCCEED = 'car/replaceCars'
export const CAR_ADDING_SUCCEED = 'car/adding'
export const CAR_ERROR = 'car/error'
export const CAR_CLEAR_ERRORS = 'car/clearErrors'
export const CAR_CURRENT_NOTE_SUCCEED = 'car/currentNote'
export const CAR_NOTE_PULL_SUCCEED = 'car/pullNote'

