///// AUTH
export const AUTH_ME = 'AUTH_ME'
export const AUTH_LOGIN = 'AUTH_LOGIN'
export const AUTH_REG = 'AUTH_REG'

///// CAR
export const CAR_DELETE = 'CAR_DELETE'
export const CAR_ADD = 'CAR_ADD'
export const CAR_CURRENT = 'CAR_CURRENT'
export const CAR_GARAGE = 'CAR_GARAGE'
export const CAR_UPDATE = 'CAR_UPDATE'
export const CAR_PHOTO = 'CAR_PHOTO'
export const CAR_NOTE_PUSH = 'CAR_NOTE_PUSH'
export const CAR_NOTE_PULL = 'CAR_NOTE_PULL'
export const CAR_NOTE_REPLACE = 'CAR_NOTE_REPLACE'


///// USER
export const USER_PROFILE = 'USER_PROFILE'
export const USER_UPDATE = 'USER_UPDATE'
export const USER_UPDATE_PHOTO = 'USER_UPDATE_PHOTO'


///// LIST
export const LIST_SUBS_USERS = 'LIST_SUBS_USERS'
export const LIST_SUBS_CARS = 'LIST_SUBS_CARS'
export const LIST_SEARCH_CARS = 'LIST_SEARCH_CARS'
export const LIST_SEARCH_USERS = 'LIST_SEARCH_USERS'
export const LIST_USER_FOLLOW = 'LIST_USER_FOLLOW'
export const LIST_CAR_FOLLOW = 'LIST_CAR_FOLLOW'
export const LIST_SUBS_USER_UNFOLLOW = 'LIST_SUBS_USER_UNFOLLOW'
export const LIST_SUBS_CAR_UNFOLLOW = 'LIST_SUBS_CAR_UNFOLLOW'
export const LIST_SEARCH_USER_UNFOLLOW = 'LIST_SEARCH_USER_UNFOLLOW'
export const LIST_SEARCH_CAR_UNFOLLOW = 'LIST_SEARCH_CAR_UNFOLLOW'




