export const PROFILE_USER_SUCCEED = 'profile/userSucceed'
export const PROFILE_PHOTO_SUCCEED = 'profile/userPhoto'
export const PROFILE_FETCHING = 'profile/fetching'
export const PROFILE_ERROR = 'profile/error'
export const PROFILE_USERS_SUCCEED = 'profile/usersSucceed'
export const PROFILE_FOLLOW_SUCCEED = 'profile/followUser'
export const PROFILE_UNFOLLOW_SUCCEED = 'profile/unfollowUser'
